/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_RocksMemEnv */

#ifndef _Included_org_rocksdb_RocksMemEnv
#define _Included_org_rocksdb_RocksMemEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_RocksMemEnv
 * Method:    createMemEnv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_RocksMemEnv_createMemEnv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksMemEnv
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksMemEnv_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
