/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_RocksDBExceptionTest */

#ifndef _Included_org_rocksdb_RocksDBExceptionTest
#define _Included_org_rocksdb_RocksDBExceptionTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_RocksDBExceptionTest
 * Method:    raiseException
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksDBExceptionTest_raiseException
  (JNIEnv *, jobject);

/*
 * Class:     org_rocksdb_RocksDBExceptionTest
 * Method:    raiseExceptionWithStatusCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksDBExceptionTest_raiseExceptionWithStatusCode
  (JNIEnv *, jobject);

/*
 * Class:     org_rocksdb_RocksDBExceptionTest
 * Method:    raiseExceptionNoMsgWithStatusCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksDBExceptionTest_raiseExceptionNoMsgWithStatusCode
  (JNIEnv *, jobject);

/*
 * Class:     org_rocksdb_RocksDBExceptionTest
 * Method:    raiseExceptionWithStatusCodeSubCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksDBExceptionTest_raiseExceptionWithStatusCodeSubCode
  (JNIEnv *, jobject);

/*
 * Class:     org_rocksdb_RocksDBExceptionTest
 * Method:    raiseExceptionNoMsgWithStatusCodeSubCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksDBExceptionTest_raiseExceptionNoMsgWithStatusCodeSubCode
  (JNIEnv *, jobject);

/*
 * Class:     org_rocksdb_RocksDBExceptionTest
 * Method:    raiseExceptionWithStatusCodeState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksDBExceptionTest_raiseExceptionWithStatusCodeState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
