/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_TransactionLogIterator */

#ifndef _Included_org_rocksdb_TransactionLogIterator
#define _Included_org_rocksdb_TransactionLogIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_TransactionLogIterator
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_TransactionLogIterator_disposeInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_TransactionLogIterator
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_TransactionLogIterator_isValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_TransactionLogIterator
 * Method:    next
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_TransactionLogIterator_next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_TransactionLogIterator
 * Method:    status
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_TransactionLogIterator_status
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_TransactionLogIterator
 * Method:    getBatch
 * Signature: (J)Lorg/rocksdb/TransactionLogIterator/BatchResult;
 */
JNIEXPORT jobject JNICALL Java_org_rocksdb_TransactionLogIterator_getBatch
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
