/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_SstPartitionerFixedPrefixFactory */

#ifndef _Included_org_rocksdb_SstPartitionerFixedPrefixFactory
#define _Included_org_rocksdb_SstPartitionerFixedPrefixFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_SstPartitionerFixedPrefixFactory
 * Method:    newSstPartitionerFixedPrefixFactory0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_SstPartitionerFixedPrefixFactory_newSstPartitionerFixedPrefixFactory0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstPartitionerFixedPrefixFactory
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstPartitionerFixedPrefixFactory_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
