/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_VectorMemTableConfig */

#ifndef _Included_org_rocksdb_VectorMemTableConfig
#define _Included_org_rocksdb_VectorMemTableConfig
#ifdef __cplusplus
extern "C" {
#endif
#undef org_rocksdb_VectorMemTableConfig_DEFAULT_RESERVED_SIZE
#define org_rocksdb_VectorMemTableConfig_DEFAULT_RESERVED_SIZE 0L
/*
 * Class:     org_rocksdb_VectorMemTableConfig
 * Method:    newMemTableFactoryHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorMemTableConfig_newMemTableFactoryHandle
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
