/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_Checkpoint */

#ifndef _Included_org_rocksdb_Checkpoint
#define _Included_org_rocksdb_Checkpoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_Checkpoint
 * Method:    newCheckpoint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_Checkpoint_newCheckpoint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_Checkpoint
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_Checkpoint_disposeInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_Checkpoint
 * Method:    createCheckpoint
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_Checkpoint_createCheckpoint
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
