/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_Cache */

#ifndef _Included_org_rocksdb_Cache
#define _Included_org_rocksdb_Cache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_Cache
 * Method:    getUsage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_Cache_getUsage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_Cache
 * Method:    getPinnedUsage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_Cache_getPinnedUsage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
