/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_CompactionJobInfo */

#ifndef _Included_org_rocksdb_CompactionJobInfo
#define _Included_org_rocksdb_CompactionJobInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    newCompactionJobInfo
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_CompactionJobInfo_newCompactionJobInfo
  (JNIEnv *, jclass);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_CompactionJobInfo_disposeInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    columnFamilyName
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_rocksdb_CompactionJobInfo_columnFamilyName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    status
 * Signature: (J)Lorg/rocksdb/Status;
 */
JNIEXPORT jobject JNICALL Java_org_rocksdb_CompactionJobInfo_status
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    threadId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_CompactionJobInfo_threadId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    jobId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_CompactionJobInfo_jobId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    baseInputLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_CompactionJobInfo_baseInputLevel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    outputLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_CompactionJobInfo_outputLevel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    inputFiles
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_rocksdb_CompactionJobInfo_inputFiles
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    outputFiles
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_rocksdb_CompactionJobInfo_outputFiles
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    tableProperties
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_rocksdb_CompactionJobInfo_tableProperties
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    compactionReason
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_rocksdb_CompactionJobInfo_compactionReason
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    compression
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_rocksdb_CompactionJobInfo_compression
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_CompactionJobInfo
 * Method:    stats
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_CompactionJobInfo_stats
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
