/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_OptionsUtil */

#ifndef _Included_org_rocksdb_OptionsUtil
#define _Included_org_rocksdb_OptionsUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_OptionsUtil
 * Method:    loadLatestOptions
 * Signature: (JLjava/lang/String;JLjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_OptionsUtil_loadLatestOptions
  (JNIEnv *, jclass, jlong, jstring, jlong, jobject);

/*
 * Class:     org_rocksdb_OptionsUtil
 * Method:    loadOptionsFromFile
 * Signature: (JLjava/lang/String;JLjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_OptionsUtil_loadOptionsFromFile
  (JNIEnv *, jclass, jlong, jstring, jlong, jobject);

/*
 * Class:     org_rocksdb_OptionsUtil
 * Method:    getLatestOptionsFileName
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_rocksdb_OptionsUtil_getLatestOptionsFileName
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
