/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_AbstractTraceWriter */

#ifndef _Included_org_rocksdb_AbstractTraceWriter
#define _Included_org_rocksdb_AbstractTraceWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_AbstractTraceWriter
 * Method:    createNewTraceWriter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_AbstractTraceWriter_createNewTraceWriter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
