/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_AbstractWalFilter */

#ifndef _Included_org_rocksdb_AbstractWalFilter
#define _Included_org_rocksdb_AbstractWalFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_AbstractWalFilter
 * Method:    createNewWalFilter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_AbstractWalFilter_createNewWalFilter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
