/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_SstFileReader */

#ifndef _Included_org_rocksdb_SstFileReader
#define _Included_org_rocksdb_SstFileReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_SstFileReader
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReader_disposeInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_SstFileReader
 * Method:    newIterator
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_SstFileReader_newIterator
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_SstFileReader
 * Method:    open
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReader_open
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_rocksdb_SstFileReader
 * Method:    newSstFileReader
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_SstFileReader_newSstFileReader
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReader
 * Method:    verifyChecksum
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReader_verifyChecksum
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_SstFileReader
 * Method:    getTableProperties
 * Signature: (J)Lorg/rocksdb/TableProperties;
 */
JNIEXPORT jobject JNICALL Java_org_rocksdb_SstFileReader_getTableProperties
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
