/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_ClockCache */

#ifndef _Included_org_rocksdb_ClockCache
#define _Included_org_rocksdb_ClockCache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_ClockCache
 * Method:    newClockCache
 * Signature: (JIZ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_ClockCache_newClockCache
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_rocksdb_ClockCache
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_ClockCache_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
