/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_IngestExternalFileOptions */

#ifndef _Included_org_rocksdb_IngestExternalFileOptions
#define _Included_org_rocksdb_IngestExternalFileOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    newIngestExternalFileOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_IngestExternalFileOptions_newIngestExternalFileOptions__
  (JNIEnv *, jclass);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    newIngestExternalFileOptions
 * Signature: (ZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_IngestExternalFileOptions_newIngestExternalFileOptions__ZZZZ
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_IngestExternalFileOptions_disposeInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    moveFiles
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_IngestExternalFileOptions_moveFiles
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    setMoveFiles
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_IngestExternalFileOptions_setMoveFiles
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    snapshotConsistency
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_IngestExternalFileOptions_snapshotConsistency
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    setSnapshotConsistency
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_IngestExternalFileOptions_setSnapshotConsistency
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    allowGlobalSeqNo
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_IngestExternalFileOptions_allowGlobalSeqNo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    setAllowGlobalSeqNo
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_IngestExternalFileOptions_setAllowGlobalSeqNo
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    allowBlockingFlush
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_IngestExternalFileOptions_allowBlockingFlush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    setAllowBlockingFlush
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_IngestExternalFileOptions_setAllowBlockingFlush
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    ingestBehind
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_IngestExternalFileOptions_ingestBehind
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    setIngestBehind
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_IngestExternalFileOptions_setIngestBehind
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    writeGlobalSeqno
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_IngestExternalFileOptions_writeGlobalSeqno
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_IngestExternalFileOptions
 * Method:    setWriteGlobalSeqno
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_IngestExternalFileOptions_setWriteGlobalSeqno
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
